# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows.
init:
    - git config --global core.autocrlf input

environment:
    matrix:
        - nodejs_version: "0.10"

install:
    - npm install

test_script:
    - npm run-script test-no-make

build: off

version: "{build}"
